### ISSUE TITLE
User Story : Initial Setup

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#14]
As a **Dev** I can **setup Django with the supporting libraries required** so that **I can start development**

## Tasks
- [x] Task 1 – Install Django
- [x] Task 2 – Install dj_database_url psycopg2 – for utilising the postgres db
- [x] Task 3 – Install django-crispy-forms – for form styling – try it with, it might be easier to manually style the forms
- [x] Task 4 – Install django-summernote – will be needed for styling the blog entries and news articles
- [x] Task 5 – Install Stripe – for testing the stripe webhooks and payments
- [x] Task 6 – Install Pillow – for images
- [x] Task 7 – Install Django-allauth – for login/logut functionality and social media connections
- [x] Task 8 – Install Django-countries – for country selection functionality on delivery/billing address
- [x] Task 9 – Install Gunicorn – for running the site in production
- [x] Task 10 – Create a requirements.txt file to maintain libraries
- [x] Task 11 – Create the Django project
- [x] Task 12 – Create the first app
