### ISSUE TITLE
User Story : Deployment

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#16]
As a **Developer** I want to  **deploy to Heroku in development** so that **I can confirm full functionality during the build process and enable testing as development takes place**

## Tasks
- [x] Task 1 - Create a new Heroku App
- [x] Task 2 - Add the database to the app resources
- [x] Task 3 - Add the secret key’s to the Heroku config vars
- [x] Task 4 - Configure the settings.py file to point at the correct env.py file in development, the os in deployment and adjust the database section to point at the correct database url from Heroku in deployment.
- [x] Task 5 - Add the Amazon AWS S3 bucket details to the env.py file and to the Heroku config vars. Access Key and Secret Access Key.
- [x] Task 6 - Add the Email user details and password to the env.py file and to the Heroku config vars.
- [x] Task 7 - Add the Stripe details to the env.py file and to the Heroku config vars. Public key, secret key and wh-secret
