### ISSUE TITLE
User Story - SEO

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#17]
As a **Site Owner** I would like **the Site content to do well in SEO** so that **it can be found easily in a web search**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that the Site is deployed
	**When** the spiders visit the Site
	**Then** there is a Sitemap to guide them
- Acceptance Criteria 2
	**Given** that the content is added to the Site
	**When** it is written
	**Then** considerations towards SEO are made

## Tasks
- [x] Task 1 - Conduct Keyword Research prior to planning out the site
- [x] Task 2 - From Keyword Research plan content requirements for the site
- [x] Task 3 - From keyword research plan site content
- [x] Task 4 - Create sitemap.xml file utilising [www.xml-sitemaps.com](http://www.xml-sitemaps.com/)
- [x] Task 5 -  Place sitemap.xml file in root directory
- [x] Task 6 - Create robots.txt file
