### ISSUE TITLE
User Story : Create Account

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#19]
As a **User** I can **create an account** so that **I don't have to re-enter my details every time I place an order**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am an unregistered User
	**When** I register my account with an email address on the register page
	**Then** the system creates me an account and advises me so
- Acceptance Criteria 2
	**Given** that I have an account
	**When** I have items in my bag and I go to checkout
	**Then** I have my address information saved
- Acceptance Criteria 3
	**Given** that I have an account
	**When** I go to the register page and input my details
	**Then** the system advises that I already have an account with the details entered

## Tasks
- [x] Task 1 - Develop the ability for users to register for an account
- [x] Task 2 - Develop ability for users to save details to their account such as address
- [x] Task 3 - Prevent multiple accounts being created for the same email address
