### ISSUE TITLE
User Story : View Account

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#20]
As a **User** I can **check my account profile** so that **I can review the information held**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I have a User account
	**When** I am logged in
	**Then** I have the option to view my account
- Acceptance Criteria 2
	**Given** that I have a User account
	**When** I go to the profile page
	**Then** everything associated with my account can be viewed
- Acceptance Criteria 3
	**Given** that I have a User account
	**When** I am not logged in and try to go to my profile URL
	**Then** I am redirected to the login page.

## Tasks
- [x] Task 1 - Develop a link in the menu that takes logged in users to their profile
- [x] Task 2 - Develop a link within the user profile page that they can use to view all other information associated with the account – previous orders, wishlist items
- [x] Task 3 -Restrict access to account details to logged in users – specifically the user who’s details they are.
