### ISSUE TITLE
User Story : Edit Account

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#21]
As a **User** I can **edit the details stored on my account** so that **I can keep my details up to date for deliveries/payment**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I have a User account
	**When** I go to my profile page
	**Then** I have the option to edit my account
- Acceptance Criteria 2
	**Given** that I have a User account
	**When** I go to my profile page
	**Then** I have the ability to have more than one address stored
- Acceptance Criteria 3
	**Given** that I have a User account
	**When** I go to my profile page
	**Then** I have the ability to edit the address
- Acceptance Criteria 4
	**Given** that I have a User account
	**When** I go to my profile page
	**Then** I can delete the address

## Tasks
- [x] Task 1 - Develop the ability for users to save addresses to their profile
- [ ] Task 2 - Develop the ability for users to store more than one address on their profile
- [x] Task 3 - Develop the ability for users to set one address as default
- [x] Task 4 - Develop the ability for users to edit the addresses on their profile
- [x] Task 5 - Develop the ability for users to delete the addresses on their profile
