### ISSUE TITLE
User Story : Delete Account

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#22]
As a **User** I can **delete my account** so that **I have control over where I want my data to be stored**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I have a User account
	**When** I go to my profile page
	**Then** I have the option to delete my account
- Acceptance Criteria 2
	**Given** that I have a User account
	**When** I select to delete my account from the profile page
	**Then** my account is deleted after confirmation

## Tasks
- [x] Task 1 - On the user profile page provide an option to delete account
- [x] Task 2 - Require a second confirmation for account deletion
- [x] Task 3 - Develop method to delete the account when the user requests it to be deleted whilst order history is kept seperately for company records.
