### ISSUE TITLE
User Story: Account Login

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#23]
As a **User** I can **login to my account** so that **I can enjoy the benefits of having an account**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a registered User
	**When** I go to the login page
	**Then** I can enter my account details to login
- Acceptance Criteria 2
	**Given** that I am a registered User
	**When** I enter my details on the login page and click to login
	**Then** I get a confirmation that I was successfully logged in 
- Acceptance Criteria 3
	**Given** that I am a registered User
	**When** I attempt to login with the incorrect details
	**Then** I am advised my details are incorrect

## Tasks
- [x] Task 1 - Develop a link to a login page
- [x] Task 2 - Develop a login form for users to confirm their log in details
- [x] Task 3 - Develop form validation to ensure the data is entered correctly
- [x] Task 4 - Develop a method to validate the data entered matches a user account
- [x] Task 5 - Develop a redirect so users that are not logged in or registered are redirected to the login page when trying to access pages that require the user to be logged in.
