### ISSUE TITLE
User Story : Account Logout

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#24]
As a **User** I can **log out of my account** so that **I can keep my account secure**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am logged in to my account
	**When** I click to logout
	**Then** I have to confirm my choice
- Acceptance Criteria 2
	**Given** that I am a logged-in user who has clicked logout
	**When** I confirm to log out
	**Then** I am logged out of my account
- Acceptance Criteria 3
	**Given** that I am a registered User who has logged out of my account
	**When** I click the back button to access a previously visited page on the site
	**Then** I cannot access information that is only available to me when logged in 

## Tasks
- [x] Task 1 - Develop link for users to access logout 
- [x] Task 2 - Develop logout confirmation form to log users out
- [x] Task 3 - Develop a redirect so if a user signs out whilst on a page requiring a user to be logged in, it redirects them appropriately
