### ISSUE TITLE
User Story : Add Products

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#25]
As a **Store Owner** I want **my staff to be able to add products to the Site** so that **products availability can be kept up to date**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am an employee
	**When** I log in to the Site
	**Then** I have options to add products to the Site
- Acceptance Criteria 2
	**Given** that I am a logged-in employee
	**When** I select to add products to the Site
	**Then** I am taken to a form to allow me to do so 
- Acceptance Criteria 3
	**Given** that I am a logged in employee
	**When** I have completed the form to add a product to the Site
	**Then** the new product(s) should appear on the site

## Tasks
- [x] Task 1 -  Develop an option on the navigation bar for employee users to allow access to other site areas
- [x] Task 2 - Develop a form for employees to add products to the site
- [x] Task 3 - Develop form validation to ensure that product information is completed correctly
- [x] Task 4 - Develop the backend to process the form data and create a new product file/page to be added to the site
