### ISSUE TITLE
User Story : Edit Products

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#26]
As a **Site Owner** I can **make changes to product details on the Site** so that **any corrections or misinformation can be amended**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am an employee
	**When** I log in to the Site
	**Then** I have the option to edit product details
- Acceptance Criteria 2
	**Given** that I am an employee
	**When** I log in and select a product to edit
	**Then** I am taken to a form to edit those details
- Acceptance Criteria 3
	**Given** that I am a logged in employee
	**When** I have made an edit to a product 
	**Then** the changes I have made appear on the site

## Tasks
- [x] Task 1 - Develop the option for employees to edit products
- [x] Task 2 - Develop a page for employees to select which product to edit
- [x] Task 3 - Develop a form for employees to edit the product data
- [x] Task 4 - Develop validation for the form to ensure product information is complete
