### ISSUE TITLE
User Story : View Product Details

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#27]
As a **shopper** I can **look at the complete product details** so that **I can make an informed decision whether to purchase**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a Shopper
	**When** I select a product to view
	**Then** the full details of that product are presented
- Acceptance Criteria 2
	**Given** that I am on the all products page
	**When** I click on a product card
	**Then** I am taken to the product details page

## Tasks
- [x] Task 1 - Develop a product full details page template
- [x] Task 2 -  Develop product card template
- [x] Task 3 - Link product card with product detail page
