### ISSUE TITLE
User Story : Product Search

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#29]
As a **Shopper** I would like to  **search for products** so that **I can easily find what I am looking for**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a User
	**When** I am on the site
	**Then** I have easy access to search function
- Acceptance Criteria 2
	**Given** that I am a User
	**When** I search for a product by name
	**Then** the product appears in the search results
- Acceptance Criteria 3
	**Given** that I am a User
	**When** I want to search by category
	**Then** all the products in the category appear

## Tasks
- [x] Task 1 - Develop search bar functionality that is easy to access on every page
- [x] Task 2 - Develop search query filter to search by product name
- [x] Task 3 - Develop search query filter to search by category
