### ISSUE TITLE
User Story : Add Product to Wishlist

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#31]
As a **Shopper** I can **add products to a personal wishlist** so that **I can quickly access/purchase the items at a later date**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a registered User
	**When** I view a product
	**Then** I have the option to save it to my wishlist
- Acceptance Criteria 2
	**Given** that I am an unregistered User
	**When** I view a product and try to add it to my wishlist
	**Then** I receive a message to register/login to have a wishlist

## Tasks
- [x] Task 1 – Develop a wishlist model linked to user
- [x] Task 2 – Develop a simple button that adds products to user’s wishlist
- [x] Task 3 – Develop a message to unregistered users to inform them that the wishlist is available to registered/logged in users
- [x] Task 4 – Develop a visual indicator to users to inform them that the product is on their wishlist
