### ISSUE TITLE
User Story : Remove product from Wishlist

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#32]
As a **User** I can **remove products from my wishlist** so that **I can remove products I no longer wish to purchase**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a registered User
	**When** I navigate to my wishlist
	**Then** I can remove items from there
- Acceptance Criteria 2
	**Given** that I am a registered User
	**When** I select a product to be removed from my wishlist
	**Then** it is removed and updated

## Tasks
- [x] Task 1 - Develop a wishlist page template to display users saved items
- [x] Task 2 - Develop ability for users to remove products from the wishlist on the wishlist page
- [x] Task 3 - Develop link for users to access wishlist page easily
- [x] Task 4 - Develop link to access product detail page from products in wishlist
