### ISSUE TITLE
User Story : Add to Cart

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#33]
As a **Shopper** I can **add products to my Cart** so that **I can purchase them**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am an unregistered User
	**When** I select a product to add to cart
	**Then** the product is added to the cart
- Acceptance Criteria 2
	**Given** that I a logged-in User
	**When**  I select a product to add to cart
	**Then** the product is added to the cart
- Acceptance Criteria 3
	**Given** that I am a User
	**When** I select an already selected product to the cart
	**Then** the quantity of the product increases in the cart accordingly
- Acceptance Criteria 4
	**Given** that I am a registred User not logged in to my account
	**When** I select products to add to my cart 
	**Then** when I log in the products are still in my cart

## Tasks
- [x] Task 1 – Develop a shopping cart functionality to track products users want to purchase.
- [x] Task 2  – Enable the cart to be utilised when a user is logged in or not
- [x] Task 3 - Develop check on add to cart functionality for product already existing in cart – if product exists, increase quantity appropriately
- [x] Task 4 – Develop ability for logged out user to login without losing cart contents.
