### ISSUE TITLE
User Story : Payment

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#37]
As a **Shopper** I can **use my preferred card to make payment** so that **I can quickly and easily purchase the product**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a Shopper 
	**When** I got to the checkout 
	**Then** I have the ability to enter my card details on a secure form
- Acceptance Criteria 2
	**Given** that I am a Shopper
	**When** I enter my card details for payment and click pay
	**Then** the system will process the payment
- Acceptance Criteria 3
	**Given** that I am a User
	**When** I request payment to be made
	**Then** I am kept updated with the status of the payment
- Acceptance Criteria 4
	**Given** that  I am a User
	**When** the payment fails
	**Then** I am taken back to the checkout page
- Acceptance Criteria 5
	**Given** that  I am a User
	**When** the payment is successful
	**Then** I am taken to the order confirmation page

## Tasks
- [x] Task 1 - – Develop secure form to capture card details
- [x] Task 2 - Develop link to payment processor
- [x] Task 3 - Develop message system to keep customer informed of processing status
- [x] Task 4 - Develop redirect to appropriate page depending on payment outcome
