### ISSUE TITLE
User Story : Order Confirmation

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#38]
As a **Shopper** I want **to be shown my order confirmation when my order has completed** so that **it is clear and obvious my order was created**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a User
	**When** I complete my order
	**Then** I am taken to the order confirmation place
- Acceptance Criteria 2
	**Given** that I am a User
	**When** the order is completed
	**Then** an email of my order confirmation is sent
- Acceptance Criteria 3
	**Given** that I am a User
	**When** the order is completed
	**Then** an order number is generated that I can use to retrieve my order details
- Acceptance Criteria 4
	**Given** that I am a logged in User
	**When** the order is completed
	**Then** I can view the order details in my account

## Tasks
- [x] Task 1 - Develop an order confirmation page that the user redirects to on order completion.
- [x] Task 2 - Develop automated email confirming order – email to include link to order details page for that order and order number
- [x] Task 3 - Develop linking new order to user orders so that it is visible within their order history on their account.
- [x] Task 4 - Develop order number generator so each number has a unique identifier
