### ISSUE TITLE
EPIC : Site Owner Objectives

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#4]
As a **Site Owner** I can **use the Site to attract customers** so that ***the Site can make a profit for the business*

## Tasks
- [ ] Capture user details
- [ ] Make product purchase available to all visitors to site
- [ ] Fully responsive site - accessible on multiple devices
