### ISSUE TITLE
User Story : Reviews

### ISSUE THREAD

**Issue by mattcooperdev** [mattcooperdev/coopgarms#40]
As a **User** I can **create, read, update, delete and reply to reviews** so that **I can share my opinion on products on the Site**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a User
	**When** I have purchased a product 
	**Then** I can leave a review
- Acceptance Criteria 2
	**Given** that I am a User
	**When** I have created a review
	**Then** it is available to read on the SIte
- Acceptance Criteria 3 
	**Given** that I am a User 
	**When** I have created a review
	**Then** I have the option to edit it
- Acceptance Criteria 4
	**Given** that I am a User
	**When** I have created a review
	**Then** I  have the option to delete it 
- Acceptance Criteria 5
	**Given** that I am a User
	**When** I have created a review
	**Then** I have the option to delete it 

## Tasks
- [ ] Task 1 -Develop product detail template to include user generated reviews
- [ ] Task 2 - Develop method for logged in users to add a review of a product they have previously purchased
- [ ] Task 3 - Develop method for review author to edit their review
- [ ] Task 4 - Develop the ability for a review author to delete their review
- [ ] Task 5 - Develop the ability for an employee to delete a review
- [ ] Task 6 - Develop a method for employees to respond to a review left on the site
